import { createClient } from 'npm:@supabase/supabase-js@2'

const corsHeaders = { 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type', 'Access-Control-Allow-Methods': 'POST, OPTIONS' }

function b64url(value: Uint8Array | string) { const bytes = typeof value === 'string' ? new TextEncoder().encode(value) : value; let binary=''; for(const b of bytes) binary+=String.fromCharCode(b); return btoa(binary).replaceAll('+','-').replaceAll('/','_').replace(/=+$/g,'') }
function pemToBytes(pem:string){const clean=pem.replace(/-----BEGIN PRIVATE KEY-----|-----END PRIVATE KEY-----|\s/g,'');const binary=atob(clean);return Uint8Array.from(binary,c=>c.charCodeAt(0))}
function b64std(bytes:Uint8Array){let binary='';for(const b of bytes)binary+=String.fromCharCode(b);return btoa(binary)}
async function googleAccessToken(sa:Record<string,string>){const now=Math.floor(Date.now()/1000);const unsigned=`${b64url(JSON.stringify({alg:'RS256',typ:'JWT'}))}.${b64url(JSON.stringify({iss:sa.client_email,scope:'https://www.googleapis.com/auth/cloud-platform',aud:'https://oauth2.googleapis.com/token',iat:now,exp:now+3600}))}`;const key=await crypto.subtle.importKey('pkcs8',pemToBytes(sa.private_key),{name:'RSASSA-PKCS1-v1_5',hash:'SHA-256'},false,['sign']);const sig=await crypto.subtle.sign('RSASSA-PKCS1-v1_5',key,new TextEncoder().encode(unsigned));const assertion=`${unsigned}.${b64url(new Uint8Array(sig))}`;const r=await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({grant_type:'urn:ietf:params:oauth:grant-type:jwt-bearer',assertion})});if(!r.ok)throw new Error(`Google OAuth token error ${r.status}`);const d=await r.json();if(!d.access_token)throw new Error('Google OAuth token missing');return d.access_token as string}
function normalize(v:string|null|undefined){return String(v||'').normalize('NFKD').replace(/[\u0300-\u036f]/g,'').toUpperCase().replace(/[^A-Z0-9 ]/g,' ').replace(/\s+/g,' ').trim()}
function nameScore(expected:string,ocr:string){const t=normalize(expected).split(' ').filter(x=>x.length>=2);if(!t.length)return 0;const h=normalize(ocr);return Math.round(t.filter(x=>h.includes(x)).length/t.length*10000)/100}
function extractDob(ocr:string){const m=ocr.match(/\b(\d{1,2})[\/-](\d{1,2})[\/-](\d{4})\b/);return m?`${m[3]}-${m[2].padStart(2,'0')}-${m[1].padStart(2,'0')}`:null}
function extractMyKad(ocr:string){const m=ocr.match(/\b\d{6}[- ]?\d{2}[- ]?\d{4}\b/);return m?`••••••-${m[0].replace(/\D/g,'').slice(6,8)}-••••`:null}
function detectIdType(ocr:string,fallback:string){const t=normalize(ocr);if(/MYKID/.test(t))return'mykid';if(/MYKAD|MALAYSIA/.test(t))return'mykad';if(/PASSPORT/.test(t))return'passport';return fallback}
function extractText(doc:any){return String(doc?.text||'')}
async function processDocument(token:string,project:string,location:string,processor:string,bytes:Uint8Array,mime:string){const endpoint=`https://${location}-documentai.googleapis.com/v1/projects/${encodeURIComponent(project)}/locations/${encodeURIComponent(location)}/processors/${encodeURIComponent(processor)}:process`;const r=await fetch(endpoint,{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify({rawDocument:{mimeType:mime,content:b64std(bytes)},imagelessMode:true,fieldMask:'text,entities,pages.pageNumber'})});if(!r.ok)throw new Error(`Document AI process error ${r.status}`);return await r.json()}

Deno.serve(async(req)=>{
 if(req.method==='OPTIONS')return new Response('ok',{headers:corsHeaders});
 try{
  const authHeader=req.headers.get('Authorization')||'';const token=authHeader.replace(/^Bearer\s+/i,'');if(!token)throw new Error('Authentication required');
  const supabaseUrl=Deno.env.get('SUPABASE_URL')!;const secretMap=Deno.env.get('SUPABASE_SECRET_KEYS');const serviceRole=secretMap?JSON.parse(secretMap).default:Deno.env.get('SUPABASE_SERVICE_ROLE_KEY');if(!serviceRole)throw new Error('Supabase server secret is not configured');
  const admin=createClient(supabaseUrl,serviceRole);const {data:auth,error:authError}=await admin.auth.getUser(token);if(authError||!auth.user)throw new Error('Invalid session');
  const body=await req.json();const kycId=String(body?.kyc_id||'');if(!kycId)throw new Error('kyc_id diperlukan');
  const {data:kyc,error:ke}=await admin.from('identity_verifications').select('id,profile_id,subject_type,id_type,legal_name_claimed,birth_state_code,document_storage_paths,status').eq('id',kycId).eq('profile_id',auth.user.id).eq('subject_type','player').maybeSingle();if(ke)throw ke;if(!kyc)throw new Error('Permohonan KYC tidak ditemui');if(kyc.status!=='pending')return new Response(JSON.stringify({ok:true,status:kyc.status,kyc_id:kyc.id}),{headers:{...corsHeaders,'Content-Type':'application/json'}});
  const paths=Array.isArray(kyc.document_storage_paths)?kyc.document_storage_paths:[];if(!paths.length||paths.length>2||paths.some((p:unknown)=>typeof p!=='string'||!p.startsWith(`${auth.user.id}/`)))throw new Error('Dokumen KYC tidak sah');
  const serviceJson=Deno.env.get('GOOGLE_SERVICE_ACCOUNT_JSON');const projectId=Deno.env.get('GOOGLE_DOCUMENT_AI_PROJECT_ID');const location=Deno.env.get('GOOGLE_DOCUMENT_AI_LOCATION')||'asia-southeast1';const processorId=Deno.env.get('GOOGLE_DOCUMENT_AI_PROCESSOR_ID');if(!serviceJson||!projectId||!processorId)throw new Error('Google Document AI belum dikonfigurasi sepenuhnya');const sa=JSON.parse(serviceJson);if(!sa.client_email||!sa.private_key)throw new Error('Google service account JSON tidak lengkap');
  await admin.from('identity_verifications').update({provider:'google_document_ai',provider_status:'processing',match_status:'not_processed',updated_at:new Date().toISOString()}).eq('id',kyc.id);
  const access=await googleAccessToken(sa);let ocr='';let detectedType=kyc.id_type;let maskedId:string|null=null;let detectedDob:string|null=null;
  for(const path of paths){const {data:file,error:de}=await admin.storage.from('kyc-documents').download(path);if(de||!file)throw new Error('Dokumen KYC tidak boleh dibaca');const bytes=new Uint8Array(await file.arrayBuffer());const mime=path.toLowerCase().endsWith('.pdf')?'application/pdf':path.toLowerCase().endsWith('.png')?'image/png':'image/jpeg';const result=await processDocument(access,projectId,location,processorId,bytes,mime);const text=extractText(result.document);ocr+=`\n${text}`;detectedType=detectIdType(text,detectedType);maskedId=maskedId||extractMyKad(text);detectedDob=detectedDob||extractDob(text)}
  const {data:player,error:pe}=await admin.from('players').select('full_name,date_of_birth').eq('profile_id',auth.user.id).eq('is_active',true).maybeSingle();if(pe)throw pe;if(!player)throw new Error('Player profile not found');
  const score=nameScore(player.full_name,ocr);const dobMatches=detectedDob?detectedDob===player.date_of_birth:true;const matchStatus=score>=90&&dobMatches?'match':score>=50||!detectedDob?'inconclusive':'mismatch';
  await admin.from('identity_verifications').update({provider:'google_document_ai',provider_status:'processed',extracted_legal_name:null,extracted_birth_date:detectedDob,extracted_id_type:detectedType,extracted_identifier_masked:maskedId,match_status:matchStatus,match_score:score,processed_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq('id',kyc.id);
  return new Response(JSON.stringify({ok:true,status:'pending',kyc_id:kyc.id,provider:'google_document_ai',provider_status:'processed',match_status:matchStatus,match_score:score,extracted_id_type:detectedType}),{headers:{...corsHeaders,'Content-Type':'application/json'}})
 }catch(e){console.error('PlayPro KYC provider error',e);return new Response(JSON.stringify({ok:false,error:e instanceof Error?e.message:'KYC processing failed'}),{status:400,headers:{...corsHeaders,'Content-Type':'application/json'}})}
})
